region              = "us-east-1"
vpc_cidr_block      = "10.0.0.0/16"
vpc_tag             = "workspace-vpc"
public_1_cidrblock  = "10.0.1.0/24"
public_2_cidrblock  = "10.0.2.0/24"
public_3_cidrblock  = "10.0.3.0/24"
az_1                = "us-east-1a"
public_subnet_1_tag = "workspace-subnet-1"
public_subnet_2_tag = "workspace-subnet-2"
public_subnet_3_tag = "workspace-subnet-3"
igw_tag             = "workspace-Igw"
rt_cidr_block       = "0.0.0.0/0"
route_table_tag     = "workspace-RouteTable"
ec2_az              = "us-east-1a"
key_name            = "aws"
env                 = "main"
  