variable "environment" {}
variable "amis" {}
variable "region" {}
variable "key_name" {}
variable "public_subnet" {}
variable "private_subnet" {}
variable "sg_id" {}
variable "public_cidr" {}
variable "private_cidr" {}
variable "vpc_tag" {}